### ISSUE TITLE
Round the window corners when KDE's window decoration is hidden

### ISSUE THREAD

**Issue by Manueljlin** [alex47/KDE-Rounded-Corners#5]
Mostly so that GTK apps like pamac and CSD apps like chromium can benefit from this.

**Comment by alex47** [comment]
Could you post some images of the issue?
I don't think I understand the problem.

**Comment by Manueljlin** [comment]
youtube.com/watch?v=1erFhljp4pY

**Comment by alex47** [comment]
Done

![Rounded Firefox with CSD](https://i.imgur.com/FCZQRHY.png)

Could you please test it?

**Comment by Manueljlin** [comment]
It works really well, thanks :D
