### ISSUE TITLE
Add latte-dock as an exception.

### ISSUE THREAD

**Issue by ChrisP4** [alex47/KDE-Rounded-Corners#6]
add latte dock as an exception so the latte-dock doesn't get round edges

**Comment by alex47** [comment]
I can't reproduce the problem

![a](https://i.imgur.com/IraKqNf.png)

Any special settings needed?

**Comment by ChrisP4** [comment]
Set the latte-dock as a panel with a full background and you have to see that it creates rounded edges. It does for me at least.

**Comment by RavenTheDev** [comment]
I can confirm this. Having it turned on with full background will cause Rounded Edges to it, but only on some themes.

**Comment by ChrisP4** [comment]
I'm using the arc theme btw

**Comment by gcjuan** [comment]
I can also confirm it ;)

![imagen](https://user-images.githubusercontent.com/19599325/52903790-0de70980-3223-11e9-87d3-db47a6ed0b74.png)
