### ISSUE TITLE
kde 5.15

### ISSUE THREAD

**Issue by brudolp** [alex47/KDE-Rounded-Corners#8]
configuration failing, I guess this is related to the 5.15 update, if you want I can give you the CMakeOutput.log, Arch/Antergos,
this is the terminal output:
[...]
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5Config: /usr/lib64/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.55.0") 
CMake Warning at /usr/share/cmake-3.13/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  Could not find a configuration file for package "KF5CoreAddons" that is
  compatible with requested version "5.55.0".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.54.0
    /usr/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.54.0
    /lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.54.0
    /lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.54.0

Call Stack (most recent call first):
  /usr/lib64/cmake/KF5Auth/KF5AuthConfig.cmake:46 (find_dependency)
  /usr/share/cmake-3.13/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
  /usr/lib64/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake:39 (find_dependency)
  /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package)
  CMakeLists.txt:33 (find_package)

CMake Warning at /usr/share/cmake-3.13/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/KF5Auth/KF5AuthConfig.cmake

  but it set KF5Auth_FOUND to FALSE so package "KF5Auth" is considered to be
  NOT FOUND.  Reason given by package:

  KF5Auth could not be found because dependency KF5CoreAddons could not be
  found.

Call Stack (most recent call first):
  /usr/lib64/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake:39 (find_dependency)
  /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package)
  CMakeLists.txt:33 (find_package)

CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake

  but it set KF5ConfigWidgets_FOUND to FALSE so package "KF5ConfigWidgets" is
  considered to be NOT FOUND.  Reason given by package:

  KF5ConfigWidgets could not be found because dependency KF5Auth could not be
  found.

Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)

-- Could NOT find KF5ConfigWidgets (found version "5.55.0"), checked the following files:
    /usr/lib64/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (version 5.55.0)
    Reason given by package: KF5ConfigWidgets could not be found because dependency KF5Auth could not be found.

-- Found KF5CoreAddons: /usr/lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.54.0") 
-- Found KF5Crash: /usr/lib64/cmake/KF5Crash/KF5CrashConfig.cmake (found version "5.55.0") 
-- Found KF5GlobalAccel: /usr/lib64/cmake/KF5GlobalAccel/KF5GlobalAccelConfig.cmake (found version "5.55.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found KF5I18n: /usr/lib64/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.55.0") 
-- Found KF5KIO: /usr/lib64/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.55.0") 
-- Found KF5Service: /usr/lib64/cmake/KF5Service/KF5ServiceConfig.cmake (found version "5.55.0") 
-- Found KF5Init: /usr/lib64/cmake/KF5Init/KF5InitConfig.cmake (found version "5.55.0") 
-- Found KF5Notifications: /usr/lib64/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.55.0") 
-- Found KF5WidgetsAddons: /usr/lib64/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfig.cmake (found version "5.55.0") 
-- Found KF5WindowSystem: /usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.55.0") 
-- Found KF5GuiAddons: /usr/lib64/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (found version "5.55.0") 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: ConfigWidgets) (found suitable version
  "5.54.0", minimum required is "5.9.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:33 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/username/KDE-Rounded-Corners/qt5build/CMakeFiles/CMakeOutput.log".

**Comment by alex47** [comment]
I tried this with latest KDE Neon and it builds without problems, even on 5.15
I believe this is distro related
Try updating your system

**Comment by brudolp** [comment]
reinstalled kf5, everything is working now
